import { chromium } from '/opt/node-tools/node_modules/playwright/index.mjs';
const d = process.argv[2], detail = process.argv[3] || '120';
const b = await chromium.launch({ executablePath: '/opt/pw-browsers/chromium', args: ['--use-gl=swiftshader','--enable-unsafe-swiftshader','--no-sandbox'] });
const p = await b.newPage({ viewport: { width: 1280, height: 800 } }); const errs = []; p.on('pageerror', e => errs.push(e.message));
await p.addInitScript(() => { window.__lag = 0; let last = performance.now(); setInterval(() => { const n = performance.now(); window.__lag = Math.max(window.__lag, n - last - 20); last = n; }, 20); });
await p.goto('file://' + process.cwd() + '/artifact.html');
const settle = () => p.waitForFunction(() => document.getElementById('busy').hidden && /Xong|lỗi/.test(document.getElementById('shStatus').textContent), null, { timeout: 300000 });
await p.waitForTimeout(600); await settle();
await p.selectOption('#detail', detail);
await p.evaluate(() => { window.__lag = 0; });
const t0 = Date.now();
await p.setInputFiles('#file', '/tmp/claude-0/tuong_gau_nang.stl');
await p.waitForFunction(() => /nghìn mặt|Không đọc|lỗi/.test(document.getElementById('toast').textContent), null, { timeout: 300000 });
console.log('toast sau', ((Date.now() - t0) / 1000).toFixed(1), 's:', await p.textContent('#toast'));
await settle();
console.log('tổng đến khi có hộp bao:', ((Date.now() - t0) / 1000).toFixed(1), 's |', await p.textContent('#shStatus'), '| lag tối đa luồng chính:', Math.round(await p.evaluate(() => window.__lag)), 'ms');
console.log((await p.innerText('#phoiInfo')).replace(/\n/g, ' | ').slice(0, 260));
console.log((await p.innerText('#shDraft')).split('\n').slice(0, 2).join(' | '));
await p.screenshot({ path: d + '/21_huge.png' });
console.log('errors', errs); await b.close();
