import { chromium } from '/opt/node-tools/node_modules/playwright/index.mjs';
const b = await chromium.launch({ executablePath: '/opt/pw-browsers/chromium', args: ['--use-gl=swiftshader','--enable-unsafe-swiftshader','--no-sandbox'] });
const p = await b.newPage({ viewport: { width: 1280, height: 800 } });
const errs = []; p.on('pageerror', e => errs.push(e.message)); p.on('console', m => m.type()==='error' && errs.push(m.text()));
await p.goto('file://' + process.cwd() + '/index.html');
await p.click('#demo');
await p.waitForTimeout(500);
await p.screenshot({ path: process.argv[2] + '/1_phoi.png' });
await p.selectOption('#n', '3'); await p.click('#autoTheta');
await p.click('#build');
await p.waitForFunction(() => /Xong|lỗi/.test(document.getElementById('status').textContent), null, { timeout: 60000 });
console.log(await p.textContent('#status'));
await p.fill('#explode', '60'); await p.dispatchEvent('#explode', 'input');
await p.uncheck('#showPhoi');
await p.waitForTimeout(500);
await p.screenshot({ path: process.argv[2] + '/2_khuon.png' });
console.log(await p.innerText('#moldInfo')); console.log(await p.innerText('#plasterInfo')); console.log(await p.innerText('#draftInfo'));
console.log('errors', errs);
await b.close();
