import { chromium } from '/opt/node-tools/node_modules/playwright/index.mjs';
const d = process.argv[2];
const b = await chromium.launch({ executablePath: '/opt/pw-browsers/chromium', args: ['--use-gl=swiftshader','--enable-unsafe-swiftshader','--no-sandbox'] });
const p = await b.newPage({ viewport: { width: 1280, height: 800 } }); const errs=[]; p.on('pageerror', e=>errs.push(e.message));
await p.goto('file://' + process.cwd() + '/artifact.html');
const done = () => p.waitForFunction(() => /Xong|lỗi/.test(document.getElementById('shStatus').textContent) && !document.getElementById('shBuild').disabled, null, { timeout: 100000 });
await done();
await p.setInputFiles('#file', 'test/tuong_gau_test.stl'); await p.waitForTimeout(800); await done();
console.log((await p.innerText('#phoiInfo')).replace(/\n/g,' | '));
console.log(await p.textContent('#shStatus'), '|', (await p.innerText('#shDraft')).replace(/\n/g,' | '));
console.log((await p.innerText('#shInfo')).replace(/\n/g,' | '));
await p.screenshot({ path: d + '/14_statue.png' });
await p.fill('#shExplode','55'); await p.dispatchEvent('#shExplode','input'); await p.waitForTimeout(500);
await p.screenshot({ path: d + '/15_statue_explode.png' });
console.log(errs); await b.close();
