import { chromium } from '/opt/node-tools/node_modules/playwright/index.mjs';
const b = await chromium.launch({ executablePath: '/opt/pw-browsers/chromium', args: ['--use-gl=swiftshader','--enable-unsafe-swiftshader','--no-sandbox'] });
const p = await b.newPage(); const errs=[]; p.on('pageerror', e=>errs.push(e.message));
await p.goto('file://' + process.cwd() + '/index.html');
await p.setInputFiles('#file', 'test/cube.stl');
await p.waitForTimeout(300);
console.log(await p.innerText('#phoiInfo'));
await p.click('#build');
await p.waitForFunction(() => /Xong|lỗi/.test(document.getElementById('status').textContent), null, {timeout:60000});
console.log(await p.textContent('#status'), '|', await p.innerText('#moldInfo'));
const [d] = await Promise.all([p.waitForEvent('download'), p.click('#dlPieces button')]);
console.log('download', d.suggestedFilename());
console.log(errs);
await b.close();
