import { chromium } from '/opt/node-tools/node_modules/playwright/index.mjs';
import { writeFileSync } from 'node:fs';
const d = process.argv[2];
const b = await chromium.launch({ executablePath: '/opt/pw-browsers/chromium', args: ['--use-gl=swiftshader','--enable-unsafe-swiftshader','--no-sandbox'] });
const p = await b.newPage({ viewport: { width: 430, height: 900 } }); const errs=[]; p.on('pageerror', e=>errs.push(e.message));
await p.addInitScript(() => { window.claude = { use: async (n) => n === 'downloads' ? { save: async ({ filename, data }) => { const buf = await data.arrayBuffer(); window.__saved = { filename, b64: (()=>{let s="";const u=new Uint8Array(buf);for(let i=0;i<u.length;i+=8192)s+=String.fromCharCode.apply(null,u.subarray(i,i+8192));return btoa(s);})() }; return { status: 'saved' }; } } : null }; });
await p.goto('file://' + process.cwd() + '/artifact.html'); await p.waitForTimeout(800);
console.log('file name text:', await p.textContent('#fileName'));
await p.click('#dlSample'); await p.waitForTimeout(1500);
const s = await p.evaluate(() => window.__saved); console.log(s.filename, s.b64.length);
writeFileSync(d + '/t.zip', Buffer.from(s.b64, 'base64'));
console.log(await p.textContent('#status')); console.log(errs); await b.close();
